spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transport
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
  thymeleaf:
    cache: false
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss